// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQG2bw4F__TgLdoHv4eK2aYNPsyhwE-c4',
    appId: '1:586590651645:web:1b6fbe3e54d365578dea94',
    messagingSenderId: '586590651645',
    projectId: 'fake-store-8da54',
    authDomain: 'fake-store-8da54.firebaseapp.com',
    storageBucket: 'fake-store-8da54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgt4JnwJ_fb7FPmiaxdAQdiay_M4FjH1E',
    appId: '1:586590651645:android:dcb8315bf3162b6f8dea94',
    messagingSenderId: '586590651645',
    projectId: 'fake-store-8da54',
    storageBucket: 'fake-store-8da54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC34fJHe4vzE0r83_gPdQjAId9qXRpKJ84',
    appId: '1:586590651645:ios:700bec0abcfd5c068dea94',
    messagingSenderId: '586590651645',
    projectId: 'fake-store-8da54',
    storageBucket: 'fake-store-8da54.firebasestorage.app',
    iosBundleId: 'com.example.arqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC34fJHe4vzE0r83_gPdQjAId9qXRpKJ84',
    appId: '1:586590651645:ios:700bec0abcfd5c068dea94',
    messagingSenderId: '586590651645',
    projectId: 'fake-store-8da54',
    storageBucket: 'fake-store-8da54.firebasestorage.app',
    iosBundleId: 'com.example.arqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQG2bw4F__TgLdoHv4eK2aYNPsyhwE-c4',
    appId: '1:586590651645:web:dcde7ae09a3de43e8dea94',
    messagingSenderId: '586590651645',
    projectId: 'fake-store-8da54',
    authDomain: 'fake-store-8da54.firebaseapp.com',
    storageBucket: 'fake-store-8da54.firebasestorage.app',
  );
}
